import { useEffect, useState } from 'react';
import { api } from '../api.js';
const empty={name:'',role:'',email:''};
export default function Members(){
 const[members,setMembers]=useState([]),[form,setForm]=useState(empty),[editId,setEditId]=useState(null),[error,setError]=useState('');const load=()=>api.list('members').then(setMembers).catch(e=>setError(e.message));useEffect(()=>{load()},[]);
 const submit=async e=>{e.preventDefault();setError('');try{editId?await api.update('members',editId,form):await api.create('members',form);setForm(empty);setEditId(null);load()}catch(err){setError(err.message)}};
 const edit=m=>{setEditId(m._id);setForm({name:m.name,role:m.role,email:m.email})};const remove=async m=>{if(confirm(`Delete ${m.name}? Their tasks will become unassigned.`)){await api.remove('members',m._id);load()}};
 return <div>{error&&<p className="error-message">{error}</p>}<form onSubmit={submit} className="card team-form"><div><label className="label">Name</label><input required className="input" placeholder="e.g. Alex Rivera" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></div><div><label className="label">Role</label><input className="input" placeholder="e.g. Product designer" value={form.role} onChange={e=>setForm({...form,role:e.target.value})}/></div><div><label className="label">Email</label><input type="email" className="input" placeholder="alex@example.com" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></div><div className="team-form-actions" style={{display:'flex',gap:5}}><button className="btn">{editId?'Save member':'＋ Add member'}</button>{editId&&<button type="button" className="btn-ghost" onClick={()=>{setEditId(null);setForm(empty)}}>Cancel</button>}</div></form>
 <div className="section-head"><h2>Your team <span style={{color:'#a1a6bb',fontSize:11,fontWeight:500}}>· {members.length} members</span></h2></div>{members.length===0?<div className="card empty-state">A good team makes all the difference. Invite your first teammate above.</div>:<div className="member-grid">{members.map(m=><article key={m._id} className="card member-card"><div className="member-actions"><button className="btn-ghost" onClick={()=>edit(m)}>Edit</button><button className="btn-ghost" style={{color:'#c05d73'}} onClick={()=>remove(m)}>Delete</button></div><div className="member-card-head"><span className="member-avatar">{m.name?.[0]?.toUpperCase()}</span><div><p className="member-name">{m.name}</p><p className="member-role">{m.role||'Team member'}</p></div></div><p className="member-email">✉　{m.email||'No email added'}</p></article>)}</div>}</div>
}
