import { useEffect, useState } from 'react';
import { api, STATUSES, PRIORITIES, fmtDate } from '../api.js';
const empty={title:'',description:'',assignee:'',priority:'Medium',deadline:'',status:'To Do'};
export default function Tasks(){
 const[tasks,setTasks]=useState([]),[members,setMembers]=useState([]),[form,setForm]=useState(null),[editId,setEditId]=useState(null),[error,setError]=useState('');
 const load=()=>Promise.all([api.list('tasks'),api.list('members')]).then(([t,m])=>{setTasks(t);setMembers(m)}).catch(e=>setError(e.message));useEffect(()=>{load()},[]);
 const open=t=>{setEditId(t?._id||null);setForm(t?{title:t.title,description:t.description,assignee:t.assignee||'',priority:t.priority,deadline:t.deadline?.slice(0,10)||'',status:t.status}:{...empty})};
 const save=async e=>{e.preventDefault();const data={...form,assignee:form.assignee||null,deadline:form.deadline||null};try{editId?await api.update('tasks',editId,data):await api.create('tasks',data);setForm(null);load()}catch(err){setError(err.message)}};
 const setStatus=async(t,status)=>{await api.update('tasks',t._id,{status});load()};const remove=async t=>{if(confirm(`Delete "${t.title}"?`)){await api.remove('tasks',t._id);load()}};
 const f=k=>({value:form[k],onChange:e=>setForm({...form,[k]:e.target.value})});const memberName=id=>members.find(m=>m._id===id)?.name||'Unassigned';
 return <div>{error&&<p className="error-message">{error}</p>}<div className="task-toolbar"><p>{tasks.length} {tasks.length===1?'task':'tasks'} in your project</p><button className="btn" onClick={()=>open()}>＋　New task</button></div>
 {form&&<div className="modal-backdrop" onClick={()=>setForm(null)}><form onSubmit={save} onClick={e=>e.stopPropagation()} className="card modal"><h2>{editId?'Edit task':'Add a new task'}</h2><div className="form-grid"><div className="form-field full"><label className="label">Task name</label><input required className="input" placeholder="What needs doing?" {...f('title')}/></div><div className="form-field full"><label className="label">A few details</label><textarea rows="3" className="input" placeholder="Add a little context..." {...f('description')}/></div><div><label className="label">Who’s on it?</label><select className="input" {...f('assignee')}><option value="">Unassigned</option>{members.map(m=><option key={m._id} value={m._id}>{m.name}</option>)}</select></div><div><label className="label">Priority</label><select className="input" {...f('priority')}>{PRIORITIES.map(p=><option key={p}>{p}</option>)}</select></div><div><label className="label">Due date</label><input type="date" className="input" {...f('deadline')}/></div><div><label className="label">Status</label><select className="input" {...f('status')}>{STATUSES.map(s=><option key={s}>{s}</option>)}</select></div></div><div className="modal-actions"><button type="button" className="btn-ghost" onClick={()=>setForm(null)}>Cancel</button><button className="btn">Save task</button></div></form></div>}
 {tasks.length===0?<div className="card empty-state">Nothing on the list yet. Create a task and get the ball rolling.</div>:<div className="task-grid">{tasks.map(t=><article key={t._id} className="card task-card"><div className="task-card-top"><div><h3 className="task-title">{t.title}</h3>{t.description&&<p className="task-desc">{t.description}</p>}</div><span className={`badge priority-${(t.priority||'Medium').toLowerCase()}`}>{t.priority}</span></div><div className="task-meta"><span className="mini-avatar">{memberName(t.assignee)[0].toUpperCase()}</span>{memberName(t.assignee)} <span>·</span> {fmtDate(t.deadline)}</div><div className="task-card-bottom"><select className="input" aria-label="Task status" value={t.status} onChange={e=>setStatus(t,e.target.value)}>{STATUSES.map(s=><option key={s}>{s}</option>)}</select><div className="task-actions"><button className="btn-ghost" onClick={()=>open(t)}>Edit</button><button className="btn-ghost" style={{color:'#c05d73'}} onClick={()=>remove(t)}>Delete</button></div></div></article>)}</div>}
 </div>
}
